name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: raiosystems

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Generate terraform.tfvars
        run: |
          echo "${{ secrets.TERRAFORMVARS }}" | base64 -d > infra/terraform.tfvars
          chmod 600 infra/terraform.tfvars

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -var-file=terraform.tfvars

      # Descomente para aplicar na main
      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve -var-file=terraform.tfvars
